api/urls.py
from django.urls import path, include
from rest_framework.authtoken.views import obtain_auth_token
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)
from . import views

urlpatterns = [
    path('', views.api_home),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path('players/', include('players.urls')),
    path('search/', include('search.urls')),
    path('forums/', include('forums.urls')),
    path('teams/', include('teams.urls')),
    path('dj-rest-auth/', include('dj_rest_auth.urls')),
    path('dj-rest-auth/registration/', include('dj_rest_auth.registration.urls')),
]

ezml_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('base.urls')),
    path('forums/', include('forums.urls')),
    path('events/', include('events.urls')),
    path('matches/', include('matches.urls')),
    path('rankings/', include('rankings.urls')),
    path('stats/', include('stats.urls')),

    path('players/', include('players.urls')),
    path('teams/', include('teams.urls')),

    path('accounts/', include('allauth.urls')),
    path('api/', include('api.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forums/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # path('list-thread', views.ThreadListView.as_view(), name='forum'),

    # path('thread/<str:pk>/', views.thread, name='thread'),
    # path('create-thread/', views.CreateThreadView.as_view(), name='create-thread'),
    # path('update-thread/<str:pk>/', views.UpdateThreadView.as_view(), name='update-thread'),
    # path('delete-thread/<str:pk>/', views.deleteThread, name='delete-thread'),

    # path('delete-comment/<str:pk>/', views.deleteComment, name='delete-comment'),
    
    # path('topics/', views.topicsPage, name='topics'),
    # path('activity/', views.activityPage, name='activity'),

    # path('<str:cat>/', views.OrderedThreadListView.as_view(), name='ordered-forum'),
    # path('<str:cat>/<str:ord>/', views.OrderedThreadListView.as_view(), name='ordered-forum'),

    # REST API
    path('', views.ThreadListCreateAPIView.as_view()),
    path('thread/<slug:slug>/', views.ThreadDetailAPIView.as_view(), name='thread'),
    path('update/<slug:slug>/', views.ThreadUpdateAPIView.as_view()),
    path('delete/<slug:slug>/', views.ThreadDeleteAPIView.as_view()),
]

forums/models.py
from django.db import models, IntegrityError
from django.contrib import admin

from django.conf import settings
from ckeditor.fields import RichTextField
from tree_queries.models import TreeNode
from django.utils.text import slugify
import random
import datetime
import pytz
import math

User = settings.AUTH_USER_MODEL
utc = pytz.utc

class Subforum(models.Model):
    name = models.CharField(max_length=200, verbose_name='Topic')

    def url_argument(self):
        return '-'.join(self.name.lower().split())

    def __str__(self):
        return self.name

class Thread(models.Model):
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    subforum = models.ForeignKey(Subforum, on_delete=models.SET_NULL, null=True)
    sticked = models.BooleanField(default=False)
    slug = models.SlugField(null=True, unique=True)

    name = models.CharField(max_length=100, verbose_name="Title")

    text_fill = RichTextField(null=True, blank=True,)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-updated', '-created']

    @property
    def get_total_likes(self):
        try:
            likes = self.likes.users.count()
        except:
            likes = 0
        return likes
    
    @property
    def get_total_dis_likes(self):
        try:
            dlikes = self.dis_likes.users.count()
        except:
            dlikes = 0
        return dlikes

    @property
    def get_hot_score(self):
        score = math.log(abs(self.get_total_likes - self.get_total_dis_likes + 0.5))
        
        now = datetime.datetime.utcnow().replace(tzinfo=utc)
        weight = (now - self.created).total_seconds()/45000
        return score/weight

    @property
    def get_top_score(self):
        score = self.get_total_likes - self.get_total_dis_likes
        return score
    
    @property
    def posted_since(self):
        now = datetime.datetime.utcnow().replace(tzinfo=utc)
        timediff = now - self.created
        return timediff.total_seconds()

    @property
    def total_comments(self):
        num_comments = self.comment_set.count()
        return num_comments

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        while True:
            try:
                return super(Thread, self).save(*args, **kwargs)
            except IntegrityError:
                r_num = random.randint(0, 100)
                self.slug = slugify(''.join(self.name, str(r_num)))
                return super(Thread, self).save(*args, **kwargs)

    def __str__(self):
        return str(self.name)

class LikeThread(models.Model):

    thread = models.OneToOneField(Thread, related_name="likes", on_delete=models.CASCADE)
    users = models.ManyToManyField(User, related_name='requirement_thread_likes')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    @admin.display(description='count')
    def get_total_likes(self):
        try:
            likes = self.users.count()
        except:
            likes = 0
        return likes

    def __str__(self):
        return str(self.thread.name)[:30]

class DisLikeThread(models.Model):

    thread = models.OneToOneField(Thread, related_name="dis_likes", on_delete=models.CASCADE)
    users = models.ManyToManyField(User, related_name='requirement_thread_dis_likes')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    @admin.display(description='count')
    def get_total_dis_likes(self):
        try:
            dlikes = self.users.count()
        except:
            dlikes = 0
        return dlikes

    def __str__(self):
        return str(self.thread.name)[:30]

class FavoriteThread(models.Model):

    thread = models.OneToOneField(Thread, related_name="fav_thread", on_delete=models.CASCADE)
    users = models.ManyToManyField(User, related_name='requirement_thread_fav')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.thread.name)[:30]

class Comment(TreeNode):
    # likes
    # Don"t forget to set parent (TreeNode)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    thread = models.ForeignKey(Thread, on_delete=models.CASCADE)
    body = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    position = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ['position', '-updated', '-created']

    def get_total_likes(self):
        return self.likes.users.count()

    def get_total_dis_likes(self):
        return self.dis_likes.users.count()

    def __str__(self):
        return self.body[0:50]

class LikeComment(models.Model):
    ''' like  comment '''

    comment = models.OneToOneField(Comment, related_name="likes", on_delete=models.CASCADE)
    users = models.ManyToManyField(User, related_name='requirement_comment_likes')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.comment.comment)[:30]

class DisLikeComment(models.Model):
    ''' Dislike  comment '''

    comment = models.OneToOneField(Comment, related_name="dis_likes", on_delete=models.CASCADE)
    users = models.ManyToManyField(User, related_name='requirement_comment_dis_likes')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.comment.comment)[:30]

forums/forms.py
from tkinter import Widget
from django.forms import ModelForm
from .models import Subforum, Thread



class ThreadForm(ModelForm):
    class Meta:
        model = Thread
        fields = '__all__'
        exclude = ['host', 'sticked']

forums/templates/forums/activity.html
{% extends 'main.html'%}

{% block content %}
<main class="layout">
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <a href="{{request.META.HTTP_REFERER}}">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>arrow-left</title>
              <path
                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
              ></path>
            </svg>
          </a>
          <h3>Recent Activities</h3>
        </div>
      </div>

      <div class="activities-page layout__body">
        {% for comment in thread_comments %}
        <div class="activities__box">
          <div class="activities__boxHeader roomListRoom__header">
            <a href="{% url 'user-profile' comment.user.id %}" class="roomListRoom__author">
              <div class="avatar avatar--small">
                <img src="https://randomuser.me/api/portraits/women/11.jpg" />
              </div>
              <p>
                {{comment.user}}
                <span>{{comment.created|timesince}}</span>
              </p>
            </a>
    
            {% if request.user == comment.user %}
            <div class="roomListRoom__actions">
              <a href="{% url 'delete-comment' comment.id %}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>remove</title>
                  <path
                    d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                  ></path>
                </svg>
              </a>
            </div>
            {% endif %}
    
          </div>
          <div class="activities__boxContent">
            <p>replied to post “<a href="{% url 'thread' comment.thread.id %}">{{comment.thread}}</a>”</p>
            <div class="activities__boxRoomContent">
                {{comment.body}}
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</main>
{% endblock content %}

forums/templates/forums/activity_component.html
<div class="activities">
    <div class="activities__header">
      <h2>Recent Activities</h2>
    </div>

    {% for comment in thread_comments %}
    <div class="activities__box">
      <div class="activities__boxHeader roomListRoom__header">
        <a href="{% url 'user-profile' comment.user.id %}" class="roomListRoom__author">
          <div class="avatar avatar--small {% if comment.user.online %}active{% endif %}">
            <img src="{{comment.user.avatar.url}}" />
          </div>
          <p>
            {{comment.user.username}}
            <span>{{comment.created|timesince}}</span>
          </p>
        </a>

        {% if request.user == comment.user %}
        <div class="roomListRoom__actions">
          <a href="{% url 'delete-comment' comment.id %}">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>remove</title>
              <path
                d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
              ></path>
            </svg>
          </a>
        </div>
        {% endif %}

      </div>
      <div class="activities__boxContent">
        <p>replied to post “<a href="{% url 'thread' comment.thread.id %}">{{comment.thread}}</a>”</p>
        <div class="activities__boxRoomContent">
            {{comment.body}}
        </div>
      </div>
    </div>
    {% endfor %}

  </div>

forums/templates/forums/forum_class.html
{% extends 'main.html'%}
{% load static %}

{% block content %}

<main class="layout layout--3">
    <div class="container">
      <!-- Topics Start -->
      {% include 'forums/subforum_component.html'%}
      
      <!-- Topics End -->
  
      <!-- Room List Start -->
      <div class="roomList">
        <div class="mobile-menu">
          <form action="{% url 'forum' %}" method="GET" class="header__search">
            <label>
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>search</title>
                <path
                  d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
                ></path>
              </svg>
              <input name="q" placeholder="Search for posts" />
            </label>
          </form>
          <div class="mobile-menuItems">
            <a class="btn btn--main btn--pill" href="{% url 'topics' %}">Browse Topics</a>
            <a class="btn btn--main btn--pill" href="{% url 'activity' %}">Recent Activities</a>
          </div>
        </div>
        <div class="roomList__header">
          <div>
            <h2>Forums</h2>
            <p>{{threads|length}} Posts</p>
          </div>
          <div class="container-sort">
              {% url 'forum' as forum_url %}

              <div class="col-sort">
                <a class="btn btn--main {% if 'new' in view.kwargs.values %} btn--dark {% endif %}" href="{{forum_url}}{% if view.kwargs and 'new' not in view.kwargs.cat %}{% if 'hot' not in view.kwargs.cat and 'top' not in view.kwargs.cat %}{{view.kwargs.cat}}/{% endif %}{% endif %}new/">
                  <img src="{% static 'images/icons/new-logo.svg'%}"/>
                  New
                </a>
              </div>
              <div class="col-sort">
                <a class="btn btn--main {% if request.get_full_path == forum_url or 'hot' in view.kwargs.values %} btn--dark {% endif %}" href="{{forum_url}}{% if view.kwargs and 'new' not in view.kwargs.cat %}{% if 'hot' not in view.kwargs.cat and 'top' not in view.kwargs.cat %}{{view.kwargs.cat}}/{% endif %}{% endif %}hot/">
                  <img src="{% static 'images/icons/hot-logo.svg'%}"/>
                  Hot</a>
              </div>
              <div class="col-sort">
                <a class="btn btn--main {% if 'top' in view.kwargs.values %} btn--dark {% endif %}" href="{{forum_url}}{% if view.kwargs and 'new' not in view.kwargs.cat %}{% if 'hot' not in view.kwargs.cat and 'top' not in view.kwargs.cat %}{{view.kwargs.cat}}/{% endif %}{% endif %}top/">
                  <img src="{% static 'images/icons/top-logo.svg'%}"/>
                  Top</a>
              </div>
  
          </div>
          <a class="btn btn--create" href="{% url 'create-thread'%}">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>add</title>
              <path
                d="M16.943 0.943h-1.885v14.115h-14.115v1.885h14.115v14.115h1.885v-14.115h14.115v-1.885h-14.115v-14.115z"
              ></path>
            </svg>
            Create Post
          </a>
        </div>
        <div class="infinite-container">
        {% include 'forums/thread_component.html'%}
        </div>
        <div class="spinner">

        </div>
        <div>
          {% if page_obj.has_next %}
          <a class="infinite-more-link" href="?page={{ page_obj.next_page_number }}"></a>
          {% endif %}
        </div>
      </div>
      <!-- Room List End -->
  
      <!-- Activities Start -->
      {% include 'forums/activity_component.html'%}
      
      <!-- Activities End -->
    </div>
  </main>

  <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'js/infinite.min.js' %}"></script>
  <script>
    var infinite = new Waypoint.Infinite({
      element: $('.infinite-container')[0],
      offset: 'bottom-in-view',
      onBeforePageLoad: function () {
        $('#mySpinner').addClass('spinner');
      },
      onAfterPageLoad: function () {
        $('#mySpinner').removeClass('spinner');
      }
    })
  </script>
    

{% endblock %}

forums/templates/forums/old_forum.html
{% extends 'main.html' %}

{% block content %}

<style>
    .forum-container{
        display: grid;
        grid-template-columns: 1fr 3fr 1fr;
    }
</style>

<div class="forum-container">   
    <div>
        {% include 'forums/subforum_component.html'%}
    </div>
    
    <div>
        <h5>{{thread_count}} Threads</h5>
        <a href="{% url 'create-thread' %}">Post Thread</a>
        {% include 'forums/thread_component.html'%}
    </div>

    <div>
        {% include 'forums/activity_component.html'%}
    </div>
</div>

{% endblock %}

forums/templates/forums/old_forum2.html
{% extends 'main.html'%}
{% load static %}

{% block content %}
<main class="layout layout--3">
  <div class="container">
    <!-- Topics Start -->
    {% include 'forums/subforum_component.html'%}
    
    <!-- Topics End -->

    <!-- Room List Start -->
    <div class="roomList">
      <div class="mobile-menu">
        <form action="{% url 'forum' %}" method="GET" class="header__search">
          <label>
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>search</title>
              <path
                d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
              ></path>
            </svg>
            <input name="q" placeholder="Search for posts" />
          </label>
        </form>
        <div class="mobile-menuItems">
          <a class="btn btn--main btn--pill" href="{% url 'topics' %}">Browse Topics</a>
          <a class="btn btn--main btn--pill" href="{% url 'activity' %}">Recent Activities</a>
        </div>
      </div>

      <div class="roomList__header">
        <div>
          <h2>Forums</h2>
          <p>{{thread_count}} Total Posts</p>
        </div>
        <div class="container-sort">
            <div class="col-sort">
              <a class="btn btn--main" href="">
                <img src="{% static 'images/icons/new-logo.svg'%}"/>
                New
              </a>
            </div>
            <div class="col-sort">
              <a class="btn btn--main" href="">
                <img src="{% static 'images/icons/hot-logo.svg'%}"/>
                Hot</a>
            </div>
            <div class="col-sort">
              <a class="btn btn--main" href="">
                <img src="{% static 'images/icons/top-logo.svg'%}"/>
                Top</a>
            </div>

        </div>
        <a class="btn btn--create" href="{% url 'create-thread'%}">
          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
            <title>add</title>
            <path
              d="M16.943 0.943h-1.885v14.115h-14.115v1.885h14.115v14.115h1.885v-14.115h14.115v-1.885h-14.115v-14.115z"
            ></path>
          </svg>
          Create Post
        </a>
      </div>

      {% include 'forums/thread_component.html'%}

    </div>
    <!-- Room List End -->

    <!-- Activities Start -->
    {% include 'forums/activity_component.html'%}
    
    <!-- Activities End -->
  </div>
</main>
{% endblock %}

forums/templates/forums/subforum_component.html
<div class="topics">
    <div class="topics__header">
      <h2>Topic List</h2>
    </div>
    <ul class="topics__list">
      <li>
        <a href="{% url 'forum' %}" class="active">All <span>{{topics.count}}</span></a>
      </li>
      {% for topic in topics %}
      <li>
        <a href="{% url 'forum'%}{{topic.url_argument}}/hot/">{{topic.name}} <span>{{topic.thread_set.all.count}}</span></a>
      </li>
      {% endfor %}
      
    </ul>
    <a class="btn btn--link" href="{% url 'topics' %}">
      More
      <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
        <title>chevron-down</title>
        <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
      </svg>
    </a>
  </div>

forums/templates/forums/thread_component.html
{% for thr in threads %}

<div class="roomListRoom infinite-item">
    <div class="roomListRoom__header">
      <a href="{% url 'user-profile' thr.host.id %}" class="roomListRoom__author">
        <div class="avatar avatar--small {% if thr.host.online %}active{% endif %}">
          <img src="{{thr.host.avatar.url}}" />
        </div>
        <span>{{thr.host.username}}</span>
      </a>
      <div class="roomListRoom__actions">
        <span>{{thr.created|timesince}}</span>
      </div>
    </div>
    <div class="roomListRoom__content">
      <div id="{{thr.id}}" class="upvotejs upvotejs-serverfault">
        <a class="upvote {% if request.user in thr.likes.users.all %}upvote-on{%endif%}"></a>
        <span class="count">{{thr.get_top_score}}</span>
        <a class="downvote {% if request.user in thr.dis_likes.users.all %}downvote-on{%endif%}"></a>
        <a class="star {% if request.user in thr.fav_thread.users.all %}star-on{%endif%}"></a>
      </div>
        <script>Upvote.create('{{thr.id}}', {callback: data => 
          {console.log(data.id);
            $.ajax({
                      type:'POST',
                      url:'{% url "forum"%}',
                      data: {
                        'csrfmiddlewaretoken': '{{ csrf_token }}',
                        'id': data.id,
                        'action': data.action,
                        'newState': data.newState
                      },
                      success: function(response){
                        console.log(response)
                      },
                      error: function(error){
                        console.log(error)
                      }
                    })
          }
          });</script>
      <div class="threadBody">
        <a href="{% url 'thread' thr.id %}">{{thr.name}}</a>
        <br>
        <a href="{% url 'thread' thr.id %}">
          <span>{{thr.description}}</span>
        </a>
      </div>     
    </div>
    <div class="roomListRoom__meta">
      <a href="{% url 'thread' thr.id %}" class="roomListRoom__joined">
        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
          <title>user-group</title>
          <path
            d="M30.539 20.766c-2.69-1.547-5.75-2.427-8.92-2.662 0.649 0.291 1.303 0.575 1.918 0.928 0.715 0.412 1.288 1.005 1.71 1.694 1.507 0.419 2.956 1.003 4.298 1.774 0.281 0.162 0.456 0.487 0.456 0.85v4.65h-4v2h5c0.553 0 1-0.447 1-1v-5.65c0-1.077-0.56-2.067-1.461-2.584z"
          ></path>
          <path
            d="M22.539 20.766c-6.295-3.619-14.783-3.619-21.078 0-0.901 0.519-1.461 1.508-1.461 2.584v5.65c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-5.651c0-1.075-0.56-2.064-1.461-2.583zM22 28h-20v-4.65c0-0.362 0.175-0.688 0.457-0.85 5.691-3.271 13.394-3.271 19.086 0 0.282 0.162 0.457 0.487 0.457 0.849v4.651z"
          ></path>
          <path
            d="M19.502 4.047c0.166-0.017 0.33-0.047 0.498-0.047 2.757 0 5 2.243 5 5s-2.243 5-5 5c-0.168 0-0.332-0.030-0.498-0.047-0.424 0.641-0.944 1.204-1.513 1.716 0.651 0.201 1.323 0.331 2.011 0.331 3.859 0 7-3.141 7-7s-3.141-7-7-7c-0.688 0-1.36 0.131-2.011 0.331 0.57 0.512 1.089 1.075 1.513 1.716z"
          ></path>
          <path
            d="M12 16c3.859 0 7-3.141 7-7s-3.141-7-7-7c-3.859 0-7 3.141-7 7s3.141 7 7 7zM12 4c2.757 0 5 2.243 5 5s-2.243 5-5 5-5-2.243-5-5c0-2.757 2.243-5 5-5z"
          ></path>
        </svg>
        {{thr.comment_set.all.count}} Commented
      </a>
      <p class="roomListRoom__topic">{{thr.subforum.name}}</p>
    </div>
</div>
{% endfor %}

forums/templates/forums/thread_form.html
{% extends 'main.html'%}

{% block content %}
<main class="create-room layout">
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <a href="{% url 'forum' %}">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>arrow-left</title>
              <path
                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
              </path>
            </svg>
          </a>
          <h3>Post a Thread</h3>
        </div>
      </div>
      <div class="layout__body">
        <form class="form" action="" method="POST">
          {% csrf_token %}
          {{ form.media }}

          {% for field in form %}
          <div class="form__group">
            <label for="room_name">{{field.label}}</label>
            {{field}}
          </div>
          {% endfor %}

          <!-- <div class="form__group">
            <label for="room_topic">Topic</label>
            <input required type="text" name="topic" id="room_topic" list="topic-list" />
            <datalist id="topic-list">
              <select id="room_topic">
                <option value="">Select your topic</option>
                <option value="Python">Python</option>
                <option value="Django">Django</option>
              </select>
            </datalist>
          </div> -->

          <div class="form__action">
            <a class="btn btn--dark" href="{% url 'forum' %}">Cancel</a>
            <button class="btn btn--main" type="submit">Submit</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</main>
{% endblock %}

forums/templates/forums/thread_form_old.html
{% extends 'main.html' %}

{% block content %}

<div>
    <form method="POST" action="">
        {% csrf_token %}
        {{ form.as_p}}

        <input type="submit" value="Submit" />
    </form>
</div>

{% endblock content %}

forums/templates/forums/topics.html
{% extends 'main.html' %}

{% block content %}
<main class="create-room layout">
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <a href="{{request.META.HTTP_REFERER}}">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>arrow-left</title>
              <path
                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
              ></path>
            </svg>
          </a>
          <h3>Browse Topics</h3>
        </div>
      </div>

      <div class="topics-page layout__body">
        <form action="" method="GET" class="header__search">
          <label>
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>search</title>
              <path
                d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
              ></path>
            </svg>
            <input name="q" placeholder="Search for topics" />
          </label>
        </form>

        <ul class="topics__list">
          
          <li>
            <a href="{% url 'forum' %}" class="active">All <span>{{topics.count}}</span></a>
          </li>
          {% for topic in topics %}
          <li>
            <a href="{% url 'forum'%}{{topic.url_argument}}/hot/">{{topic.name}} <span>{{topic.thread_set.all.count}}</span></a>
          </li>
          {% endfor %}
          
        </ul>
      </div>
    </div>
  </div>
</main>
{% endblock content %}